/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.rlabs.secreter;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.rlabs.secreter.business.GenerateEnvVarService;
import com.rlabs.secreter.domain.Vars;
import java.util.Map;

public class App {
  private static final ObjectMapper mapper = new ObjectMapper();

  public static void main(String[] args) {

    GenerateEnvVarService service = new GenerateEnvVarService();

    try {

      if (System.getenv("SECRETS") != null
          && System.getenv("VARS") != null
          && System.getenv("SUFIX") != null) {

        Vars vars = mapper.readValue(System.getenv("VARS"), Vars.class);
        Map<String, Object> secrets = mapper.readValue(System.getenv("SECRETS"), Map.class);
        String sufix = System.getenv("SUFIX");

        service.generateOutput(vars, secrets, sufix);
      } else {
        System.out.println("secrets, sufix and vars are mandatory");
        System.exit(17);
      }
    } catch (JsonMappingException e) {
      e.printStackTrace();
      System.exit(3);
    } catch (JsonProcessingException e) {
      e.printStackTrace();
      System.exit(5);
    }
  }
}
